name: PaStiX with MPI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: v2.17_build
    - name: install MPI
      run: sudo apt update && sudo apt install libopenmpi-dev openmpi-bin openmpi-common mpich -y
    - name: install pthreads (necessary ?)
      run: sudo apt-get install libpthread-stubs0-dev -y
      
    - name: install CUDA (why ???)
      run: sudo apt install nvidia-cuda-toolkit nvidia-cuda-dev libcupti-dev -y
      
    - name: Fetch CCX source & unpack it
      run: |
        cd /usr/local/ && sudo wget http://www.dhondt.de/ccx_2.17.src.tar.bz2 && 
        sudo bunzip2 ccx_2.17.src.tar.bz2 && sudo tar -xvf ccx_2.17.src.tar
        
    - name: Install Boost Threads (required ?)
      run: sudo apt install libboost-thread-dev -y
        
    - name: Build PaStiX dependencies - OpenBLAS
      run: |
        cd ~ && git clone https://github.com/xianyi/OpenBLAS.git && mv OpenBLAS ./OpenBLAS_i8 && pwd && ls &&
        cd OpenBLAS_i8 && make -j 8 INTERFACE64=1 && sudo make install
        
        
    - name: Download hwloc 2.1.0
      run: mkdir -p ~/PaStiX/ && cd ~/PaStiX/ && wget https://download.open-mpi.org/release/hwloc/v2.1/hwloc-2.1.0.tar.bz2
      
    - name: Unpack hwloc and copy the build script
      run: |
        cd ~/PaStiX && bunzip2 hwloc-2.1.0.tar.bz2 && tar -xf hwloc-2.1.0.tar && 
        sudo cp /usr/local/CalculiX/ccx_2.17/src/make_hwloc.sh ~/PaStiX/hwloc-2.1.0/make_hwloc.sh
        
    - name: Run the build script
      run: |
        cd ~/PaStiX/hwloc-2.1.0 && echo $HOME &&
        umask 022 && 
        ./configure --prefix=$HOME/PaStiX/hwloc_i8 CC=gcc CXX=g++ &&
        make -j8
        
    - name: Install hwloc
      run:  cd ~/PaStiX/hwloc-2.1.0 && make install
      
      
    - name: Download parsec
      run: cd ~/PaStiX && git clone -b pastix-6.0.2 --single-branch https://bitbucket.org/mfaverge/parsec.git && ls
      
    - name: Copy the build script and run it
      run: | 
        sudo cp /usr/local/CalculiX/ccx_2.17/src/make_parsec.sh ~/PaStiX/parsec &&
        cd ~/PaStiX/parsec && 
        sudo chmod 777 make_parsec.sh && 

        if ! [[ -d build ]]; then
            mkdir build
        fi
        cd build &&

        export INSTALLPATH="~/PaStiX/parsec_i8"&&
        umask 022 &&

        # fixes
        sed -i '/-1 == cpu/i return cpu;' parsec/bindthread.c &&

        cmake \
        -DCMAKE_CXX_COMPILER=g++ \
        -DCMAKE_C_COMPILER=gcc \
        -DCMAKE_Fortran_COMPILER=gfortran \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=${INSTALLPATH} \
        -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-10.2 \
        -DCUDA_DIR=/usr/local/cuda-10.2 \
        -DCUDA_USE_STATIC_CUDA_RUNTIME=OFF \
        -DCMAKE_CUDA_HOST_COMPILER=gcc \
        -DPARSEC_GPU_WITH_CUDA=OFF \
        -DHWLOC_DIR=~/PaStiX/hwloc_i8 \
        .. &&
        make -j8 && 
        rm -rf ${INSTALLPATH} &&
        make install

        
        
    - name: Download scotch_6.0.8 and unpack
      run: |
        cd ~/PaStiX &&
        wget https://gforge.inria.fr/frs/download.php/file/38114/scotch_6.0.8.tar.gz &&
        tar -xf scotch_6.0.8.tar.gz
        
    - name: Copy the build script and run it
      run: |
        sudo cp /usr/local/CalculiX/ccx_2.17/src/make_scotch.sh ~/PaStiX/scotch_6.0.8 &&
        cd ~/PaStiX/scotch_6.0.8 &&
        sudo chmod 777 ./make_scotch.sh &&
        ./make_scotch.sh
        
    - name: Inspect folders
      run: |
        echo "Home folder : " &&
        ls ~/PaStiX &&
        echo "Root folder : " &&
        sudo ls /root/
        
    - name: Clone PaStiX and the buildscript
      run: |
        cd ~/PaStiX &&
        git clone https://github.com/boris-martin/PaStiX4CalculiX &&
        ls ~/PaStiX/hwloc_i8 &&
        mv ./PaStiX4CalculiX/ ./pastix_src &&
        sudo cp /usr/local/CalculiX/ccx_2.17/src/make_pastix.sh ~/PaStiX/pastix_src &&
        cd pastix_src && git submodule init && git submodule update &&
        sudo cat ./make_pastix.sh
        
    - name: Run PaStiX script
      run: |
        cd ~/PaStiX/pastix_src &&
        if ! [[ -d build ]]; then
            mkdir build
        fi &&
        cd build &&
        cmake \
        -DBLAS_DIR=~/OpenBLAS_i8 \
        -DHWLOC_DIR=~/PaStiX/hwloc_i8 \
        -DCMAKE_INSTALL_PREFIX=~/PaStiX/pastix_i8 \
        -DCMAKE_BUILD_TYPE=Release \
        -DPASTIX_WITH_PARSEC=ON \
        -DPARSEC_DIR=~/PaStiX/parsec_i8 \
        -DSCOTCH_DIR=~/PaStiX/scotch_i8 \
        -DPASTIX_ORDERING_SCOTCH=ON \
        -DPASTIX_WITH_CUDA=OFF \
        -DPASTIX_WITH_MPI=ON \
        -DCMAKE_C_COMPILER=gcc \
        -DCMAKE_CXX_COMPILER=g++ \
        -DCMAKE_Fortran_COMPILER=gfortran \
        -DCMAKE_C_FLAGS="-fopenmp" \
        .. &&

        make -j8 &&
        make install
        
    - name: Test Working dir
      run: pwd
      working-directory: /
