name: Calculix 2.17 with PaStiX

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: v2.17_build
    - name: Fetch CCX source & unpack it
      run: cd /usr/local/ && sudo wget http://www.dhondt.de/ccx_2.17.src.tar.bz2 && sudo bunzip2 ccx_2.17.src.tar.bz2 && sudo tar -xvf ccx_2.17.src.tar
    - name: Build PaStiX dependencies - OpenBLAS
      run: cd ~ && git clone https://github.com/xianyi/OpenBLAS.git && mv OpenBLAS ./OpenBLAS_i8 cd OpenBLAS_i8 && make -j 8 INTERFACE64=1

