name: Calculix 2.17 with preCICE adapter test build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: deb
    - name: get preCICE
      run: wget https://github.com/precice/precice/releases/download/v2.2.0/libprecice2_2.2.0_focal.deb &&
        sudo apt install ./libprecice2_2.3.0_focal.deb -y
    - name: install dependencies
      run: sudo apt install libarpack2-dev libspooles-dev libyaml-cpp-dev -y
    - name: Download Calculix
      run: wget http://www.dhondt.de/ccx_2.17.src.tar.bz2
    - name: Unpack Calculix
      run: bzip2 -d ccx_2.17.src.tar.bz2 && tar -xf ccx_2.17.src.tar
    - run: echo "CCX=$(pwd)/CalculiX/ccx_2.17/src" >> $GITHUB_ENV
    - name: Show paths
      run: echo "${{env.CCX}}" && ls "${{env.CCX}}"
    - name: make
      run: make -j 4 CCX=${CCX}
    - name: Test run
      run: ./bin/ccx_preCICE -h
    - name: Store binary artifact
      uses: actions/upload-artifact@v2
      with:
        name: ccx_preCICE
        path: ./bin/ccx_preCICE
    # - name: Create Debian Package
    #   run: |
    #          mkdir -p packaging/calculix-precice_2.17-1_amd64/usr/bin &&
    #          cp ./bin/ccx_preCICE ./packaging/calculix-precice_2.17-1_amd64/usr/bin/ccx_preCICE &&
    #          cd packaging && pwd && ls -al calculix-precice_2.17-1_amd64/ && dpkg-buildpackage -us -uc calculix-precice_2.17-1_amd64
    # - name: Store Debian Package
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: calculix-precice_2.17-1_amd64.deb
    #     path: ./packaging/calculix-precice_2.17-1_amd64.deb
    # - name: Inspect package with lintian
    #   run: sudo apt install lintian -y && lintian ./packaging/calculix-precice_2.17-1_amd64.deb
